pull_request_rules:
  - name: forge from PR branch
    conditions:
      - label=inject-trigger
    actions:
      review:
        type: APPROVE
        message: "injected"
        bot_account: "Pockriglian"
