queue_rules:
  - name: default
    merge_conditions: []

pull_request_rules:
  - name: impersonate an outside user
    conditions:
      - label=impersonate
    actions:
      comment:
        message: "posted by Mergify acting as a user who is not in this organization"
        bot_account: "Pockriglian"
